# Generated by Django 2.2.7 on 2019-11-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number_of_traces', models.IntegerField(default=0)),
                ('number_of_events', models.IntegerField(default=0)),
                ('number_of_activities', models.IntegerField(default=0)),
                ('avg_activities_per_trace', models.FloatField(default=0)),
                ('max_activities_per_trace', models.FloatField(default=0)),
                ('mean_duration', models.CharField(default='0 days', max_length=100)),
                ('max_duration', models.CharField(default='0 days', max_length=100)),
                ('sf', models.CharField(default='simple', max_length=10)),
                ('tv', models.CharField(default='stedy', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RunningCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('prefix', models.CharField(max_length=250)),
                ('suffix', models.CharField(max_length=250)),
            ],
        ),
    ]
