# Generated by Django 2.2.7 on 2019-11-20 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191119_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runningcase',
            name='prefixes',
        ),
    ]
