# Generated by Django 2.2.7 on 2019-11-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191119_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_number', models.IntegerField(default=0)),
                ('activity_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='sf',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='tv',
        ),
        migrations.RemoveField(
            model_name='role',
            name='name',
        ),
        migrations.RemoveField(
            model_name='runningcase',
            name='name',
        ),
        migrations.RemoveField(
            model_name='runningcase',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='runningcase',
            name='suffix',
        ),
        migrations.RemoveField(
            model_name='time',
            name='name',
        ),
        migrations.AddField(
            model_name='role',
            name='role_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='role',
            name='role_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='runningcase',
            name='prefix_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='time',
            name='max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='time',
            name='mean',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='time',
            name='min',
            field=models.IntegerField(default=0),
        ),
    ]
