# Generated by Django 2.2.7 on 2019-11-25 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191120_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='running_case',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.RunningCase'),
        ),
        migrations.AddField(
            model_name='role',
            name='activity',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Activity'),
        ),
        migrations.AddField(
            model_name='runningcase',
            name='event_log',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.EventLog'),
        ),
        migrations.AddField(
            model_name='time',
            name='activity',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Activity'),
        ),
    ]
