# Generated by Django 3.0.1 on 2020-01-11 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_result_trainedmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
    ]
