# Generated by Django 3.0.1 on 2020-01-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_id', models.IntegerField(default=0)),
                ('other_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RoleSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_id', models.IntegerField(default=0)),
                ('other_id', models.IntegerField(default=0)),
            ],
        ),
    ]
