# Generated by Django 3.0.1 on 2020-01-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_activitysequence_rolesequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='activity',
        ),
        migrations.AddField(
            model_name='eventlog',
            name='activities',
            field=models.ManyToManyField(to='api.Activity'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='roles',
            field=models.ManyToManyField(to='api.Role'),
        ),
        migrations.AddField(
            model_name='runningcase',
            name='role_sequences',
            field=models.ManyToManyField(to='api.RoleSequence'),
        ),
    ]
