# Generated by Django 3.0.1 on 2020-01-14 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_runningcase_activity_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_sequence',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.RoleSequence'),
        ),
    ]
