# Generated by Django 3.0.1 on 2020-01-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_activity_activity_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysequence',
            name='roles',
            field=models.ManyToManyField(to='api.Role'),
        ),
    ]
