# Generated by Django 3.0.1 on 2020-01-16 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_activitysequence_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='running_case',
        ),
    ]
