# Generated by Django 3.0.1 on 2020-01-16 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_activity_running_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runningcase',
            name='activity_sequences',
        ),
        migrations.RemoveField(
            model_name='runningcase',
            name='role_sequences',
        ),
        migrations.AddField(
            model_name='runningcase',
            name='activity_sequence_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.ActivitySequence'),
        ),
        migrations.AddField(
            model_name='runningcase',
            name='role_sequence_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.RoleSequence'),
        ),
    ]
