# Generated by Django 3.0.1 on 2020-01-17 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_runningcase_event_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningcase',
            name='event_log',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.EventLog'),
        ),
    ]
