# Generated by Django 3.0.1 on 2020-01-17 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_runningcase_event_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runningcase',
            name='event_log',
        ),
        migrations.AddField(
            model_name='runningcase',
            name='event_log_name',
            field=models.ForeignKey(db_column='name', default='', on_delete=django.db.models.deletion.CASCADE, to='api.EventLog'),
        ),
    ]
