# Generated by Django 3.0.1 on 2020-01-17 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200117_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningcase',
            name='event_log',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='api.EventLog'),
        ),
        migrations.AlterField(
            model_name='runningcase',
            name='event_log_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
