# Generated by Django 3.0.1 on 2020-01-18 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200117_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runningcase',
            name='event_log_name',
        ),
    ]
