# Generated by Django 3.0.1 on 2020-01-18 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_runningcase_event_log_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runningcase',
            name='event_log',
        ),
    ]
