# Generated by Django 3.0.1 on 2020-01-18 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200118_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runningcase',
            name='event_log',
        ),
    ]
