# Generated by Django 3.0.1 on 2020-01-18 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_runningcase_event_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningcase',
            name='event_log',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='api.EventLog'),
        ),
    ]
