# Generated by Django 3.0.1 on 2020-01-18 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200118_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runningcase',
            name='activity_sequence_id',
        ),
        migrations.RemoveField(
            model_name='runningcase',
            name='event_log_id',
        ),
        migrations.RemoveField(
            model_name='runningcase',
            name='role_sequence_id',
        ),
    ]
